Repository Team997Coders/spartanLib2, pull requests merged in 2022-11, with the labels that each got.

#8 Logger rewrite
  src/main/java/frc/team997/lib/loggers/BooleanLogger.java
  src/main/java/frc/team997/lib/loggers/DoubleLogger.java
  src/main/java/frc/team997/lib/loggers/StringLogger.java
  src/main/java/frc/team997/lib/telemetry/HighLevelLogger.java
  src/main/java/frc/team997/lib/telemetry/Logger.java
  src/main/java/frc/team997/lib/util/DashboardChooser.java
  src/test/java/frc/team997/lib/util/DashboardChooserTests.java
Labels: cleanup

#14 Publish Javadocs to GH Actions
  .github/workflows/docs.yml
  .gitignore
  build.gradle
  scripts/pre-commit
  src/main/java/frc/team997/lib/telemetry/HighLevelLogger.java
  src/main/java/frc/team997/lib/trajectory/AsymmetricTrapezoidProfile.java
  src/main/java/frc/team997/lib/trajectory/ProfilePhase.java
Labels: documentation

#16 Publish Javadocs to GH Actions
  .github/workflows/docs.yml
  .gitignore
  build.gradle
  scripts/pre-commit
  src/main/java/frc/team997/lib/telemetry/HighLevelLogger.java
  src/main/java/frc/team997/lib/trajectory/AsymmetricTrapezoidProfile.java
  src/main/java/frc/team997/lib/trajectory/ProfilePhase.java
Labels: documentation

#13 Partial filter rewrite + differentiating filter
  src/main/java/frc/team997/lib/math/DifferentiatingFilter.java
  src/main/java/frc/team997/lib/math/Filter.java
  src/main/java/frc/team997/lib/math/PeakDetectionFilter.java
  src/test/java/frc/team997/lib/math/DifferentiatingFilterTests.java
  src/test/java/frc/team997/lib/math/PeakDetectionFilterTests.java
Labels: enhancement, cleanup

#18 docs cleanup
  LICENSE
  LICENSE.md
  build.gradle
  src/main/java/frc/team997/lib/math/Filter.java
  src/main/java/frc/team997/lib/math/MultiPointInterpolator.java
  src/main/java/frc/team997/lib/math/PeakDetectionFilter.java
  src/main/java/frc/team997/lib/math/UtilityMath.java
  src/main/java/frc/team997/lib/telemetry/HighLevelLogger.java
  src/main/java/frc/team997/lib/telemetry/Logger.java
  src/main/java/frc/team997/lib/trajectory/AsymmetricTrapezoidProfile.java
  src/main/java/frc/team997/lib/trajectory/MotionProfile.java
  src/main/java/frc/team997/lib/trajectory/ProfilePhase.java
  src/main/java/frc/team997/lib/util/DashboardChooser.java
  src/main/java/frc/team997/lib/util/GearRatioHelper.java
  src/test/java/frc/team997/lib/trajectory/MotionProfileTests.java
  src/test/java/frc/team997/lib/util/DashboardChooserTests.java
Labels: documentation, cleanup

#19 readme!
  README.md
Labels: documentation

#20 Update maven metadata for publishing
  .github/workflows/docs.yml
  .github/workflows/main.yml
  LICENSE.md
  build.gradle
Labels: cleanup

#22 Gradle fixups
  .gitignore
  build.gradle
Labels: cleanup, ci

#26 Fix problems surrounding logging
  src/main/java/org/chsrobotics/lib/telemetry/DashboardChooser.java
  src/main/java/org/chsrobotics/lib/telemetry/HighLevelLogger.java
  src/main/java/org/chsrobotics/lib/telemetry/Logger.java
  src/test/java/org/chsrobotics/lib/telemetry/DashboardChooserTests.java
Labels: bug, cleanup
