Repository Team997Coders/spartanLib2, pull requests merged in 2022-12, with the labels that each got.

#30 small tweaks/ readme pass
  .github/workflows/docs.yml
  .github/workflows/main.yml
  README.md
  src/main/java/org/chsrobotics/lib/controllers/MotionProfilePID.java
  src/main/java/org/chsrobotics/lib/controllers/PID.java
  src/main/java/org/chsrobotics/lib/telemetry/Logger.java
Labels: documentation, enhancement, cleanup, ci

#34 javadoc fixes
  src/main/java/org/chsrobotics/lib/commands/ConditionalConsumerCommand.java
  src/main/java/org/chsrobotics/lib/commands/ConditionalEndConsumerCommand.java
  src/main/java/org/chsrobotics/lib/commands/ConditionalEndRunnableCommand.java
Labels: bug

#32 Add differential drive mode abstractions
  README.md
  build.gradle
  src/main/java/org/chsrobotics/lib/drive/differential/ArcadeDrive.java
  src/main/java/org/chsrobotics/lib/drive/differential/CurvatureDrive.java
  src/main/java/org/chsrobotics/lib/drive/differential/DifferentialDriveMode.java
  src/main/java/org/chsrobotics/lib/drive/differential/DifferentialDrivetrainInput.java
  src/main/java/org/chsrobotics/lib/drive/differential/MixedDrive.java
  src/main/java/org/chsrobotics/lib/drive/differential/TankDrive.java
  src/main/java/org/chsrobotics/lib/input/JoystickAxis.java
  src/main/java/org/chsrobotics/lib/input/JoystickButton.java
  src/main/java/org/chsrobotics/lib/math/filters/RateLimiter.java
  src/main/java/org/chsrobotics/lib/telemetry/DashboardChooser.java
  src/test/java/org/chsrobotics/lib/drive/differential/DifferentialDriveInputTests.java
  src/test/java/org/chsrobotics/lib/drive/differential/DifferentialDriveModeTests.java
Labels: enhancement

#29 bug fixes + array support for logger
  src/main/java/org/chsrobotics/lib/telemetry/HighLevelLogger.java
  src/main/java/org/chsrobotics/lib/telemetry/Logger.java
Labels: bug, enhancement, cleanup

#35 1.1.0
  .github/workflows/docs.yml
  .github/workflows/main.yml
  .gitignore
  README.md
  build.gradle
  src/main/java/org/chsrobotics/lib/commands/ConditionalConsumerCommand.java
  src/main/java/org/chsrobotics/lib/commands/ConditionalEndConsumerCommand.java
  src/main/java/org/chsrobotics/lib/commands/ConditionalEndRunnableCommand.java
  src/main/java/org/chsrobotics/lib/commands/ConditionalRunnableCommand.java
  src/main/java/org/chsrobotics/lib/commands/ConsumerCommand.java
  src/main/java/org/chsrobotics/lib/commands/LogMessageCommand.java
  src/main/java/org/chsrobotics/lib/commands/RunnableCommand.java
  src/main/java/org/chsrobotics/lib/controllers/MotionProfilePID.java
  src/main/java/org/chsrobotics/lib/controllers/PID.java
  src/main/java/org/chsrobotics/lib/drive/differential/ArcadeDrive.java
  src/main/java/org/chsrobotics/lib/drive/differential/CurvatureDrive.java
  src/main/java/org/chsrobotics/lib/drive/differential/DifferentialDriveMode.java
  src/main/java/org/chsrobotics/lib/drive/differential/DifferentialDrivetrainInput.java
  src/main/java/org/chsrobotics/lib/drive/differential/MixedDrive.java
  src/main/java/org/chsrobotics/lib/drive/differential/TankDrive.java
  src/main/java/org/chsrobotics/lib/input/JoystickAxis.java
  src/main/java/org/chsrobotics/lib/input/JoystickButton.java
  src/main/java/org/chsrobotics/lib/input/VirtualJoystickButton.java
  src/main/java/org/chsrobotics/lib/input/XboxController.java
  src/main/java/org/chsrobotics/lib/math/UtilityMath.java
  src/main/java/org/chsrobotics/lib/math/filters/DifferentiatingFilter.java
  src/main/java/org/chsrobotics/lib/math/filters/Filter.java
  src/main/java/org/chsrobotics/lib/math/filters/PeakDetectionFilter.java
  src/main/java/org/chsrobotics/lib/math/filters/RateLimiter.java
  src/main/java/org/chsrobotics/lib/math/filters/ThresholdFilter.java
  src/main/java/org/chsrobotics/lib/telemetry/DashboardChooser.java
  src/main/java/org/chsrobotics/lib/telemetry/HighLevelLogger.java
  src/main/java/org/chsrobotics/lib/telemetry/Logger.java
  src/main/java/org/chsrobotics/lib/trajectory/MotionProfile.java
  src/main/java/org/chsrobotics/lib/util/GearRatioHelper.java
  src/main/java/org/chsrobotics/lib/util/Tuple2.java
  src/test/java/org/chsrobotics/lib/controllers/MotionProfilePIDTests.java
  src/test/java/org/chsrobotics/lib/controllers/PIDTests.java
  src/test/java/org/chsrobotics/lib/drive/differential/DifferentialDriveInputTests.java
  src/test/java/org/chsrobotics/lib/drive/differential/DifferentialDriveModeTests.java
  src/test/java/org/chsrobotics/lib/input/JoystickAxisTests.java
  src/test/java/org/chsrobotics/lib/input/JoystickButtonTests.java
  src/test/java/org/chsrobotics/lib/input/VirtualJoystickButtonTests.java
  src/test/java/org/chsrobotics/lib/math/UtilityMathTests.java
  src/test/java/org/chsrobotics/lib/math/filters/DifferentiatingFilterTests.java
  src/test/java/org/chsrobotics/lib/math/filters/PeakDetectionFilterTests.java
  src/test/java/org/chsrobotics/lib/math/filters/RateLimiterTests.java
  src/test/java/org/chsrobotics/lib/math/filters/ThresholdFilterTests.java
  src/test/java/org/chsrobotics/lib/telemetry/DashboardChooserTests.java
  src/test/java/org/chsrobotics/lib/util/TupleTests.java
Labels: bug, documentation, enhancement, cleanup, ci

#40 Bug Fix Release
  build.gradle
  scripts/pre-commit
  src/main/java/org/chsrobotics/lib/input/XboxController.java
  src/main/java/org/chsrobotics/lib/telemetry/HighLevelLogger.java
Labels: bug
